version: 2
updates:
  - package-ecosystem: gradle
    target-branch: 1.3.x
    directory: /
    schedule:
      interval: weekly
      day: sunday
    allow:
      - dependency-name: org.apache.kafka:kafka-clients
      - dependency-name: io.micrometer:micrometer-core
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    open-pull-requests-limit: 10
    labels:
      - 'type/dependency-upgrade'

  - package-ecosystem: gradle
    target-branch: 1.3.x
    directory: /
    schedule:
      interval: weekly
      day: sunday
    ignore:
      - dependency-name: '*'
    labels:
      - 'type/chores'
    groups:
      development-dependencies:
        update-types:
          - patch
        patterns:
          - '*'
        exclude-patterns:
          - org.apache.kafka*
          - io.micrometer:micrometer-core
          - io.micrometer:micrometer-observation
          - com.google.code.findbugs:jsr305

  - package-ecosystem: github-actions
    target-branch: 1.3.x
    directory: /
    schedule:
      interval: weekly
      day: sunday
    labels:
      - 'type/chores'
    groups:
      development-dependencies:
        patterns:
          - '*'
